POST {{url}}/blog
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "mi first fetchData en nestjs 7",
  "content": "This is the content of my fetchData",
  "description": "This is the description of my fetchData",
  "image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fb0fli8nhqpaj98qv3xsl.png",
  "published": true,
  "slug": "mi-first-fetchData-en-nestjs",
  "tags": [
    "nestjs",
    "typescript",
    "javascript"
  ],
  "views": 100,
  "readingTime": 10,
  "popular": false,
  "category": "6812d7d65e43064b0c5cfb52"
}

###

GET {{url}}/blog
Content-Type: application/json

###
GET {{url}}/blog/total
Content-Type: application/json

